# Navigation Links

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "People"
  url = "#people"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "News"
  url = "#posts"
  weight = 50

[[main]]
  name = "Teaching"
  url = "teaching"
  weight = 60

[[main]]
  name = "Software"
  url = "software"
  weight = 70

#[[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 80
